---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1ue7sv0rgz36g69haa8fr5wffu06xp6j6uak6363lwwmlpp25evwqfk5pf0"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ue7sv0rgz36g69haa8fr5wffu06xp6j6uak6363lwwmlpp25evwqfk5pf0"
